### ISSUE TITLE
ls fails

### ISSUE THREAD

**Issue by SeanSanker** [iostreamer-X/Awkward#2]
```
 ~>ººº<~: awkward
wavey@awk ward:~$ ls

/Users/wavey/.nvm/versions/node/v6.2.1/lib/node_modules/awkward/terminal/format.coffee:17
    lines = data.split('\n');
                 ^

TypeError: data.split is not a function
  at module.exports (/Users/wavey/.nvm/versions/node/v6.2.1/lib/node_modules/awkward/terminal/format.coffee:10:16)
  at /Users/wavey/.nvm/versions/node/v6.2.1/lib/node_modules/awkward/terminal/core.coffee:20:7
  at Socket.<anonymous> (/Users/wavey/.nvm/versions/node/v6.2.1/lib/node_modules/awkward/terminal/core.coffee:14:5)
  at emitOne (events.js:101:20)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:172:18)
  at Socket.Readable.push (_stream_readable.js:130:10)
  at Pipe.onread (net.js:542:20)
```

**Comment by iostreamer-X** [comment]
Is it the only command which fails? Which OS do you have?

**Comment by SeanSanker** [comment]
I'm running OSX 10.11.5.
I was running Node v6.1.0 but am now on Node v6.3.0.

The application now runs as expected for full inputs like `ls().forEach((i)=>{console.log(i)})`. 😄

Although if I don't specify a console.log line, for example, just `ls()`, the command fails with:

```
wavey@awk ward:~$ ls()
Error: Command failed: ls()
/bin/sh: -c: line 1: syntax error: unexpected end of file
```

Is this expected?

**Comment by iostreamer-X** [comment]
Oh that is expected!
Currently only this syntax is supported `ls().forEach((i)=>{console.log(i)})`

**Comment by iostreamer-X** [comment]
Hey! It turns out in Node v6+ exec returns Buffer rather than a string, which caused `TypeError: data.split is not a function`.
Fixed the issue and pushed it on npm. Please update the app and try again.

**Comment by SeanSanker** [comment]
Awesome! 
Speedy fix!

Let me go check it out.

**Comment by SeanSanker** [comment]
Works for me!

**Comment by iostreamer-X** [comment]
Awesome!
