### ISSUE TITLE
Windows bad username

### ISSUE THREAD

**Issue by icetee** [iostreamer-X/Awkward#6]
Unfortunately, when you start, the username writes that undefined.

![awkward](https://cloud.githubusercontent.com/assets/1855340/17112048/90705db8-52a4-11e6-9408-8bc46263a549.PNG)

**Comment by iostreamer-X** [comment]
Actually awkward was not built keeping Windows in mind. But I think `require('os').hostname()` will get the username on both windows and linux. So, feel free to submit a pull request!

**Comment by iostreamer-X** [comment]
Actually awkward wasn't built keeping Windows in mind. That said, if you want to add support for it, feel free to submit a pull request. Not sure but maybe this could work with [cash](https://github.com/dthree/cash) in windows!
